### ISSUE TITLE
Maven treat failed tests as error

### ISSUE THREAD

**Issue by notnoop** [teigen/scalatest-junit4runner#1]
scalatest throws `TestFailedException` for failed exceptions, while tools expect `AssertionError` for failures.  Tools would treat any other exception as an Error rather than a failure, som maven treats scala failed tests as errors.

The following patch fixes the problem:

<pre><code>
diff --git a/src/main/java/com/jteigen/scalatest/JUnit4Runner.scala b/src/main/j
index 7138e00..0512e33 100644
--- a/src/main/java/com/jteigen/scalatest/JUnit4Runner.scala
+++ b/src/main/java/com/jteigen/scalatest/JUnit4Runner.scala
@@ -56,7 +56,11 @@ class JUnit4Runner(clazz: Class[Suite]) extends Runner {
 
     override def testFailed(report: Report) {
       val desc = Description.createTestDescription(clazz, report.name)
-      notifier.fireTestFailure(new Failure(desc, report.throwable.get))
+      val throwable = report.throwable.get
+      val assertion = if (throwable.isInstanceOf[TestFailedException])
+                        new AssertionError(throwable.getMessage, throwable)
+                        else throwable
+      notifier.fireTestFailure(new Failure(desc, assertion))
       notifier.fireTestFinished(desc)
     }
</code></pre>

The behavior is event when running the following test when maven:

```
@RunWith(classOf[JUnit4Runner])
class ZazTest extends Spec with MustMatchers {
    describe("The test") {
        it("should succeed") { assert(1 == 1) }

        it ("should fail while using assert") { assert(1 == 2) }

        it ("should fail while using must") { 1 must be(2) }

        it ("should error with unexpected error") { throw new RuntimeException() }
    }
}
```

I'm using maven 3 by the way.

**Comment by notnoop** [comment]
I created a fork to handle this case along with README.markdown formatting

**Comment by teigen** [comment]
thanks for reporting. It is fixed now (http://github.com/teigen/scalatest-junit4runner/commit/2b8ca8dcddf581de622cb26f0507b492fe5d25be)

By the way, the junit4runner became an official part of ScalaTest 1.0. I recomend using that as its properly maintained.
